name: al_ameen_employer_app
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  animations: ^2.0.8
  cloud_firestore: ^4.12.2
  cupertino_icons: ^1.0.2
  device_preview: ^1.1.0
  firebase_auth: ^4.12.1
  firebase_core: ^2.21.0
  flutter:
    sdk: flutter
  flutter_slidable: ^3.0.1
  get_it: ^7.6.4
  intl: ^0.18.1
  provider: ^6.0.5
  rename: ^3.0.1
  shared_preferences: ^2.2.2
  sizer: ^2.0.15

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/al-ameen-employer-app-logo.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: RobotoCondensed
      fonts:
        - asset: assets/fonts/RobotoCondensed-Regular.ttf
